### ISSUE TITLE
Exclude ipv6?

### ISSUE THREAD

**Issue by izeen** [synackray/vcenter-netbox-sync#110]
Hello!

How do we exclude the ipv6 adress from VMs from being synced to netbox? Do we just omit the field like so:

 IPV6_ALLOWED = []

Or is it not possible? Sorry if my question is stupid and thanks in advance!

**Comment by synackray** [comment]
Hello @izeen! That is correct. If you do not place any addresses in the `IPV6_ALLOWED` listed then no IPv6 addresses will be synced.

**Comment by izeen** [comment]
Thanks for the quick reply, a follow up question on that. If i have synced everything with ipv6, if i then omit the field and sync again will they get removed or do i run the program with the --cleanup option first and then sync again?

Thank you!

**Comment by synackray** [comment]
It should automatically detect that they are "orphaned" and remove them. If not please let me know. Thanks!

**Comment by izeen** [comment]
just a follow up, i did remove the ipv6 adress in IPV6_ALLOWED = [] and re-ran the sync. They did not get removed however, so i ran the cleanup(which had another issue which i posted in a new post) and resynced and now they are not there :)
