### ISSUE TITLE
Traceback error when collecting information on disconnected vCenter host

### ISSUE THREAD

**Issue by dkuhnAtHome** [synackray/vcenter-netbox-sync#3]
### Environment
* Python version:  Python 3.6.9
* NetBox version: v2.6.8
* vCenter NetBox Sync version:  v1.0.0-rc

### Steps to Reproduce
1.  Disconnect a vCenter host
2. Execute run.py
3. Error gets thrown when collecting interface object info

### Expected Behavior
Ignoring disconnected hosts

### Observed Behavior

```
Traceback (most recent call last):
  File "run.py", line 1087, in <module>
    main()
  File "run.py", line 47, in main
    nb.sync_objects(vc_obj_type="hosts")
  File "run.py", line 791, in sync_objects
    vc_objects = self.vc.get_objects(vc_obj_type=vc_obj_type)
  File "run.py", line 348, in get_objects
    for pnic in obj.config.network.pnic:
AttributeError: 'NoneType' object has no attribute 'network'
```

**Comment by synackray** [comment]
That's a fantastic find! I'm looking into this. Thanks so much!

**Comment by synackray** [comment]
@dkuhnAtHome I perused through pyVmomi and I'm admittedly not in love with the http_client and session handler. I've added exception handling for these and a few other cases.

I was however not able to specifically replicate what you've done. When I go into vCenter and disconnect a host, vCenter still returns a cached instance of its data with the exception of status being returned as disconnected. 

Would you mind telling me your vCenter version and whether you're doing anything different? If you're comfortable feel free to run the latest commit in `develop` branch (0881c142cde5ac2b7c88c8aac08f238094dcd553) and let me know if it's better. I'll hold on merging this in until I can test this further and ideally match your case 100%. Thanks!

**Comment by synackray** [comment]
I was able to reproduce and successfully saw exceptions being skipped and then picked up on the next run when available. I'll go ahead and merge this in. Please feel free to report back if you see otherwise. I'll leave it open for a few days.
