### ISSUE TITLE
Generic banned asset tags are not accounting for word case

### ISSUE THREAD

**Issue by phbureau** [synackray/vcenter-netbox-sync#31]
Hello,
First of all thanks for this wonderful plugin ;!

I have tried to import two esxi devices (cisco b200m5). 
It works fine for the first one but not for the second one.
I saw that the first has an "asset tag" which is "UNKNOWN". -->> 

And here is the error :

```
[WARNING] NetBox failed to create devices object. A duplicate record may exist or the data sent is not acceptable.
2020-01-14 11:00:27,294 [DEBUG] NetBox 400 status reason: {'asset_tag': ['device with this Asset tag already exists.']}
2020-01-14 11:00:27,294 [DEBUG] Unaccepted request data: {'name': 'esx002', 'device_type': {'model': 'UCSB-B200-M5'}, 'device_role': {'name': 'Server'}, 'platform': {'name': 'VMware ESXi'}, 'site': {'name': 'vCenter'}, 'serial': 'xxxx', 'asset_tag': 'UNKNOWN', 'cluster': {'name': 'xxxx}, 'status': 1, 'tags': ['Synced', 'vCenter', 'xxxx']}
```

So I understood that these two machines got the same asset tag (UNKNOWN) which is not acceptable.

Have you got an idea on how I could set another asset tag ? 

Thanks for you replies :)

**Comment by synackray** [comment]
Hi @phbureau! Thanks for the report. You're spot on that the asset tags must be unique. I have a an existing banned asset tag word list to match against for situations like these. Let me make a few adjustments and I'll have an update for you shortly.

**Comment by synackray** [comment]
I've updated the banned asset tag check to account for case. `Unknown` is already disallowed and now it should catch. I'm going to place this in the `develop` branch for now, run it through full testing, and then I'll promote it into `master` seeing as this is a very minor adjustment.

**Comment by phbureau** [comment]
I retried with your develop branch, it is working very well, no more errors !
Thank you very much for your reactivity !
