### ISSUE TITLE
Add already exist esxi-hosts in netbox to cluster object in netbox

### ISSUE THREAD

**Issue by inetman28** [synackray/vcenter-netbox-sync#37]
**Is your feature request related to a problem? Please describe.**

If esxi-hosts already exist in netbox with correct fqdn then this host actualize after run vcenter-netbox-sync (physical and virtual interfaceses), but host not added to cluster.

**Describe the solution you'd like**
We have already created early esxi-hosts in netbox.

**Additional context**
![Screenshot_1](https://user-images.githubusercontent.com/45913745/72595169-42bf7d00-391a-11ea-9103-7eb3af7c7f80.png)
![Screenshot_2](https://user-images.githubusercontent.com/45913745/72595170-42bf7d00-391a-11ea-9ab6-d00e231736c1.png)

its occurs because already created esxi-hosts already have device_type but vcenter-netbox-sync want to set device type that was created automatically.

2020-01-17 13:14:53,964 [DEBUG] Sending PUT to 'http://netbox-test.local/api/dcim/devices/162/'
2020-01-17 13:14:54,439 [WARNING] NetBox failed to modify devices object with status 400. The data sent may not be acceptable.

```
obj_model = truncate(obj.summary.hardware.model, max_len=50)
```
should add exception for it if device already have device_type

**Comment by synackray** [comment]
Hello @inetman28! I'll review the details of this and try to reproduce the situation. If I am understanding correctly, you have pre-created ESXi hosts inside of NetBox and I see that you have also manually created interfaces. You would like the behavior that the manually created ESXi hosts are properly added to the cluster they belong to.

As you've shown the script is able to identify the host and place the synced interfaces inside of it but it is erroring out when trying to send a PUT to the device. Would you be able to provide me the details of the PUT data? There should be a line right around those logs messages that says, `Unaccepted request data` with the details. Thank you!

**Comment by inetman28** [comment]
yes, I can

`
2020-01-16 13:54:11,762 [DEBUG] Unaccepted request data: {'name': 'vs202.myserver.local', 'device_type': {'model': 'UCSC-C480'}, 'device_role': {'name': 'Server'}, 'platform': {'name': 'VMware ESXi'}, 'site': {'name': 'vCenter'}, 'serial': 'XXXXXXXX', 'asset_tag': 'CL-MGMT-01', 'cluster': {'name': 'CL-MGMT-01'}, 'status': 1, 'tags': ['Synced', 'vCenter', 'vc-mgmt-01']}
`

Also I note that if already esxi-hosts exist in netbox like manually created then we can change put method to patch and update filds which I want, for example, I modify code to patch only below data to netbox:
`
{
  "device_role": 8,
  "site": 1,
  "cluster": {"name": "MGMT-CLU"}
}
`

also I note some incorrect required fields in netbox api:
![image](https://user-images.githubusercontent.com/45913745/72670042-b9a76380-3a49-11ea-858f-ad5c03c8ced7.png)

the field device type and device role is not required and may be skipped when we use patch method

**Comment by synackray** [comment]
Hello, @inetman28! I am still getting feedback on this. One of the general rules I've been trying to stick to is that any objects which are synced should not overwrite manually created objects without explicit permission. This ensures we try to still follow the guidelines of NetBox and do not risk "damaging" the reputation of data inserted when a human has already manually entered it in. 

Perhaps we could add something like an optional feature for this.

**Comment by synackray** [comment]
Hello again, @inetman28! I have made an update in 5d8b529d3a39675d6816b9e4a15f5de039597c7d to enable this functionality. We will now send a PATCH for only the fields deemed relevant. If you find there are additional fields being overwritten that you would prefer are not please just let me know. Thanks!
