### ISSUE TITLE
Python error run.py

### ISSUE THREAD

**Issue by thiagoferr** [synackray/vcenter-netbox-sync#38]
### Environment
* Python version:  3.7.5
* NetBox version: v2.6.11
* vCenter version: 6.7.0.3
* vCenter NetBox Sync version:  v1.1.0

### Steps to Reproduce
1. python3 virtual environment defined
2. defined settings in setting.py
3. python3 run.py -v

### Expected Behavior

Sync all objects from vCenter and complete script running.

### Observed Behavior

When I execute run.py the sync and authentication is apparently right. But it is ocorring the error below in the half of script. Looks a python script error.

```
2020-01-20 17:46:01,780 [INFO] Verifying all prerequisite objects exist in NetBox.
[...]
> 2020-01-20 17:46:02,964 [INFO] Initiated sync of vCenter host objects to NetBox.
> 2020-01-20 17:46:02,964 [INFO] Collecting vCenter host objects.
> 2020-01-20 17:46:03,008 [INFO] Collecting info about vCenter hosts 'layan03.netservicos.corp' object.
> 2020-01-20 17:46:03,083 [DEBUG] Collecting info to create NetBox manufacturers object.
> 2020-01-20 17:46:03,127 [DEBUG] Collecting info to create NetBox device_types object.
> 2020-01-20 17:46:03,127 [DEBUG] Collecting info to create NetBox devices object.
> 2020-01-20 17:46:03,171 [DEBUG] Banned asset tag string. Nulling.
> 2020-01-20 17:46:03,236 [DEBUG] Collecting info to create NetBox interfaces object.
> 2020-01-20 17:46:03,819 [DEBUG] Collecting info for physical interface 'vmnic0'.
> Traceback (most recent call last):
>   File "run.py", line 1240, in <module>
>     main()
>   File "run.py", line 48, in main
>     nb.sync_objects(vc_obj_type="hosts")
>   File "run.py", line 901, in sync_objects
>     vc_objects = self.vc.get_objects(vc_obj_type=vc_obj_type)
>   File "run.py", line 443, in get_objects
>     pnic.validLinkSpecification[0].speedMb
> IndexError: list index out of range
```

**Comment by synackray** [comment]
Hello, @thiagoferr! Thanks for the report. I'll start reviewing and get back to you with an update.

**Comment by synackray** [comment]
I've created the `38-better-link-speed-detection` branch for this and posted a potential fix in commit fe91ad46c8fff60ce6f99d8d9775527d3cb8f2d6. I am going to run this through all normal testing then promote it to `develop` for full regression testing.

Feel free to grab the branch and test as well if you'd like. Your feedback would be much appreciated. Thanks!

**Comment by thiagoferr** [comment]
Hello, @synackray 
I downloaded the branch, It's funcional! All VMs were sync.

Thank you!

**Comment by synackray** [comment]
Fantastic news! Tests have also passed here, so I'll put this into `develop` and setup the workflows to get it promoted to `master`. Have a great day!
