### ISSUE TITLE
Query DNS for PTR lookups and populate dns_name field for IP address objects

### ISSUE THREAD

**Issue by klaver** [synackray/vcenter-netbox-sync#42]
I would like to know if it's possible to add a DNS query for each IP address found, to resolve it's PTR record and store the result to the dns_name field?

**Comment by synackray** [comment]
Helllo @klaver! I very much like this idea. :+1: I will play around with adding this as an optional feature that can be controlled through `settings.py`.

**Comment by abhilashchinthalapudi** [comment]
This would be a great add-on.
@synackray  Not sure if I need to request a new feature request ,want to check it here before I open one,
Is there a possibility to add primary_ip assignment as well so that the IP shows up under the virtual Machines List?

**Comment by synackray** [comment]
I see you opened a feature for it. I'll reply in detail there. Thanks!

**Comment by synackray** [comment]
@klaver I have been playing around with the reverse DNS lookups and could use your feedback. I'm at a bit of a crossroad. Without bringing in additional libraries I can gather PTRs in a synchronous fashion. This offers simplicity and does not require existing users to download new libraries when the release is published. However, if PTR lookups fail then it can significantly increase the execution time. I've provided some test results below.

```
Final PTR results: 9 successes | 11 failures
Total time: 41.916s

Final PTR results: 11 successes | 9 failures
Total time: 30.735s

Final PTR results: 20 successes | 0 failures
Total time: 4.711s

Final PTR results: 0 successes | 20 failures
Total time: 69.648s
```

Alternatively, I can import an async capable library that allows multiple lookups at the same time. This is faster but also means everyone who updates needs to be certain they install the latest requirements.

Right now I'm leaning towards setting the entire dns name field lookup as an optional setting in `settings.py` and using only the standard libraries, but I'd love additional feedback. Thanks for your insight!

**Comment by klaver** [comment]
@synackray I'm aware implementations differ a lot, at my current job every assigned IP address should have a reverse DNS record set, when one or two are missing it woudn't have much impact for us running this script. But I can imagine others might have a different setup where it could couse major delays. Maybe you could implement the synchronous variant for now, and add async somewhere in the future with a new major release?

**Comment by synackray** [comment]
Thanks so much for the feedback. I've continued to do some testing and will have an update this weekend.

**Comment by synackray** [comment]
Hi @klaver! I've implemented the PTR lookups into `42-reverse-dns-lookup-ip-addresses`. It has passed all of the late branch-level testing, so I will likely be merging it into `develop` by the end of this weekend. Please feel free to give it a spin and provide feedback. 

New `settings.py` variables needed
```
POPULATE_DNS_NAME = True  # Perform reverse DNS lookup on all eligible IP addresses and populate DNS name field in NetBox
CUSTOM_DNS_SERVERS = False # Use custom DNS servers defined below
DNS_SERVERS = ["192.168.1.11", "192.168.1.12"] # [optional] List of DNS servers to query for PTR records
```

**Comment by synackray** [comment]
I've promoted this to the `develop` branch pending full regression testing. This and a few other recent features will trigger an upcoming major release.

**Comment by klaver** [comment]
@synackray Thanks! I'll give it a try tonight

**Comment by klaver** [comment]
@synackray it worked like a charm!

**Comment by synackray** [comment]
That's what I like to hear! I'll be moving this into `master` on the upcoming release.
