### ISSUE TITLE
can't place server in existing rack

### ISSUE THREAD

**Issue by acaronmd** [synackray/vcenter-netbox-sync#49]
When syncing, all found items (servers, vms, clusters) are stored in a site named vCenter. This doesn't allow me to place the servers found into existing racks located in my existing sites, unless I remove the servers/clusters from the vCenter site, but if I do, I imagine I'll get dupes on the next sync. Is the vCenter site necessary to pull all of this together?

**Comment by synackray** [comment]
Hi, @acaronmd! The site is necessary on the creation of objects as it is a required field. Other than that, there is no particular reason it would be needed after after the fact. 

Let me take some time to review the object structures and be certain there would be no negative impact to ignoring the site field after creation. I very much like your idea of allowing the hardware to be placed in the right racks once they've been synced in.

**Comment by synackray** [comment]
I believe I've sorted out all needed components to allow for modifications to the site and rack details. If you don't mind would give the latest commit in `49-synced-object-locations` a test? If all is well I plan to promote this to `develop` by the end of the week, run through full regression testing, and package up a new release. Thanks!

**Comment by synackray** [comment]
Merged into `develop` branch and will promote to `master` in the next release.

**Comment by acaronmd** [comment]
Hi @synackray, I was planning on testing this for you as you had requested. I believe it's good so far. I had to ensure the clusters and devices belonged to the site I wanted, but the sync hasn't altered anything, least I haven't noticed yet.

**Comment by synackray** [comment]
This is fantastic news. Thank you so much!
