### ISSUE TITLE
Feature request: make device_role configurable via settings.py

### ISSUE THREAD

**Issue by klaver** [synackray/vcenter-netbox-sync#69]
Currently device_role is hardcoded in run.py and set to "Server". To distinguish our Hypervisors from traditional Server hardware, we rather label them with a different role in NetBox.

**Comment by synackray** [comment]
Great idea. I'll set that up.

**Comment by synackray** [comment]
Hello @klaver! I've added the following option to `settings.py` and parse it in `run.py`. Would you mind giving me your feedback? Thanks!

```
# Specify custom NetBox Device / vCenter Host role. Must match the name of an existing NetBox Device Role.
DEVICE_ROLE = "Server"
```

**Comment by klaver** [comment]
I can confirm this works as expected

**Comment by synackray** [comment]
Thanks! I'll get this moved through the process.
