### ISSUE TITLE
asset_tag mismatch

### ISSUE THREAD

**Issue by acaronmd** [synackray/vcenter-netbox-sync#72]
### Environment
* Python version:  3.6.8
* NetBox version: 2.7.6
* vCenter version: 6.7.0
* vCenter NetBox Sync version:  1.1.0

### Steps to Reproduce
1. python run.py -v

### Observed Behavior

`Mismatch: vc_data[asset_tag] value is '                                ' while nb_data[asset_tag] value is 'None'.`

`[CRITICAL] Well this in unexpected. Please report this. PATCH request received 500 status with body '{'name': 'ribstone.example.local', 'device_role': {'name': 'Server'}, 'device_type': {'model': 'ProLiant DL360 Gen9'}, 'platform': {'name': 'VMware ESXi'}, 'serial': 'XXXXXXXXXX', 'asset_tag': '                                ', 'cluster': {'name': 'ribstone.example.local'}, 'status': 'active', 'tags': ['vCenter', 'vcenter', 'Synced']}'`

One of my hosts returns '                       ' as an asset tag (there are a bunch more spaces between the quotes than what appears here). When the sync pushes this to the API, it gets a 500 error

<pre><strong>&lt;class &#39;django.db.utils.IntegrityError&#39;&gt;</strong><br />
duplicate key value violates unique constraint &quot;dcim_device_asset_tag_key&quot;
DETAIL:  Key (asset_tag)=() already exists.
</pre>

Doing an asset_tag.strip() on line 526 fixes my issue, but not sure if it's the right way to go about it.

**Comment by synackray** [comment]
Hi @acaronmd! Thanks for the report. If you're not specifically populating hardware asset tags it would be harmless to set `ASSET__TAGS = False` in `settings.py`.  Blank space asset tags should be getting dropped already, so I'll have to play around with that a little bit. There are in fact two checks for this but clearly it still somehow go through. 

Code for reference if you see any opportunities for improvement.
```
def is_banned_asset_tag(text):
    """
    Determines whether the text is a banned asset tag through various tests.

    :param text: Text to be checked against banned asset tags
    :type text: str
    :return: `True` if a banned asset tag else `False`
    :rtype: bool
    """
    # Is asset tag in banned list?
    text = text.lower()
    banned_tags = [
        "Default string", "NA", "N/A", "None", "Null", "Unknown", " ", ""
        ]
    banned_tags = [t.lower() for t in banned_tags]
    if text in banned_tags:
        result = True
    # Does it exceed the max allowed length for NetBox asset tags?
    elif len(text) > 50:
        result = True
    # Does asset tag contain all spaces?
    elif text.replace(" ", "") == "":
        result = True
    # Apparently a "good" asset tag :)
    else:
        result = False
    return result
```

**Comment by synackray** [comment]
Ahh I see a mistake in the steps that call this function. I'll get this patched immediately.

**Comment by synackray** [comment]
Merged into `develop` and will be hotfixed into `master` after regression testing.

**Comment by acaronmd** [comment]
Thanks for the quick fix! Working good on my end now.
