### ISSUE TITLE
Bug creating interfaces for esx hosts

### ISSUE THREAD

**Issue by lanbugs** [synackray/vcenter-netbox-sync#91]
### Environment
* Python version:  3.6.8
* NetBox version: 2.7.12
* vCenter version: 6.0.0
* vCenter NetBox Sync version:  1.1.0

### Steps to Reproduce
1. Start sync

### Expected Behavior
All interfaces of esx host shoud be created

### Observed Behavior
Sync should create all interfaces but only physical interfaces are created. Virtual interfaces are not created and leads to error 400.

> 2020-04-09 13:21:27,297 [DEBUG] Sending GET to 'https://netbox/api/dcim/interfaces/?device=server1234&name=vmk1' with data 'None'.
> 2020-04-09 13:21:27,320 [DEBUG] Received HTTP Status 200.
> 2020-04-09 13:21:27,321 [DEBUG] NetBox GET request OK; returned 200 status.
> 2020-04-09 13:21:27,321 [INFO] Netbox interfaces 'vmk1' object not found. Requesting creation.
> 2020-04-09 13:21:27,321 [DEBUG] Sending POST to 'https://netbox/api/dcim/interfaces/' with data '{'device': {'name': 'server1234'}, 'name': 'vmk1', 'mtu': 1500, 'mac_address': 'c0:ff:ee:c0:ff:ee', 'tags': ['Synced', 'vCenter', 'esxhost1']}'.
> 2020-04-09 13:21:27,332 [DEBUG] Received HTTP Status 400.
> 2020-04-09 13:21:27,332 [WARNING] NetBox failed to create interfaces object. A duplicate record may exist or the data sent is not acceptable.
> 2020-04-09 13:21:27,332 [DEBUG] NetBox 400 status reason: {"type":["This field is required."]}

**Comment by synackray** [comment]
@lanbugs My apologies for the delay in getting back to you. The script should be creating both physical and virtual interfaces. This error is starting there is a missing field `type` and therefore it cannot continue.

It looks like this has been recently changed in the NetBox project. I checked on NetBox v2.6.11 and `type` was not required as marked below, however it is required when testing on NetBox v2.8.1. 

I will get this patched.

NetBox v2.6.11
![image](https://user-images.githubusercontent.com/24757919/80367672-d09cf380-888b-11ea-9229-3ecbdf8d8558.png)

NetBox v2.8.1
![image](https://user-images.githubusercontent.com/24757919/80367991-4e60ff00-888c-11ea-9a02-3e593229f9c4.png)

**Comment by synackray** [comment]
This has been merged into `develop` after successful testing.
