### ISSUE TITLE
Virtual Machines that does not exist in vCenter are not being Tagged as Orphaned

### ISSUE THREAD

**Issue by abhilashchinthalapudi** [synackray/vcenter-netbox-sync#92]
Hello 

I am not able to remove the VM's that are removed from vCenter but not from Netbox. 
The only change I made in the code was to change site name from vCenter to our site name.

I have had the correct settings as per Documentation.Could you help me in fixing this ,I am not sure how the Removed VM;s are tagged as Orphaned

**Comment by abhilashchinthalapudi** [comment]
Does the Script consider Unregister Times of the VM in vcenter to mark it as orphaned.
If so I think the VM was deleted sometime back and as I do not have the script run on a schedule it did not tag them properly 

Let me know if that is case 
Thank you

**Comment by Haeki** [comment]
The script only checks netbox objects with the vc_tag to make sure nothing manually created gets wrongly deleted.
 This tag is determined by the vCenter Host. Either its the IP or a formatted version of the host name.

**Comment by synackray** [comment]
@abhilashchinthalapudi It's a pleasure to meet you. What are the following options set to in your `settings.py`?

```
# Automatically orphan and delete objects if they are no longer in their source system
NB_PRUNE_ENABLED = True
# How many days should to wait before pruning an orphaned object
NB_PRUNE_DELAY_DAYS = 0
```

**Comment by abhilashchinthalapudi** [comment]
@synackray Nice to meet you .

I am using the same settings as above 

# Automatically orphan and delete objects if they are no longer in their source system
NB_PRUNE_ENABLED = True
# How many days should to wait before pruning an orphaned object
NB_PRUNE_DELAY_DAYS = 0

Sometimes I would see VM deletes missing if I miss running the Script regularly

**Comment by synackray** [comment]
So with those settings you should have no delay in the deletion of the VMs if they have an orphaned tag. When you run the script it will eventually go through the pruning process and return a log similar to what is pasted below. Are you seeing this log? If so, are you seeing any `ERROR` or `WARNING` log entries after it? Would you mind pasting them if you do? Thanks!

Example Log
```
2020-05-07 19:00:34,719 [INFO] Comparison completed. 17 ip_addresses orphaned NetBox objects did not match.
...
2020-05-07 19:00:51,838 [INFO] Comparison completed. 10 virtual_machines orphaned NetBox objects did not match.
```

**Comment by abhilashchinthalapudi** [comment]
I did not see this happen after setting a cronjob to run every few hours.I will try to reproduce this and post the info here.
