### ISSUE TITLE
Calling device_interface with itype=0 Returns Object without type attribute

### ISSUE THREAD

**Issue by Haeki** [synackray/vcenter-netbox-sync#98]
### Environment
* Python version:  3.6.9
* NetBox version: 2.8.0
* vCenter version: 6.7.0
* vCenter NetBox Sync version:  1.1.0

### Steps to Reproduce
1. call device_interface in templates/netbox.py with parameter `itype = 0`
2. The object returned by the function has no type attribute

Expected behavior:
since the NetBox api version is greater than 2.6 the itype attribute should be set to "virtual".

Cause: 
Since itype is optional `_version_dependent()` should only be called if itype is not None.
Currently this is done by checking `"type": self._version_dependent(...) if itype else None`.  Since if 0 is evaluated as false this sets type to be None. 

Solution:
Replace ` if itype else None` with `if itype is not None else None`

**Comment by synackray** [comment]
Hello @Haeki!

Thanks for the contribution. I realized this mistake when fixing #91. I've patched it and pulled it into `develop` through #97. Would you mind giving it a review? You'll see I opted to remove the optional as this was change in the upstream NetBox project to a required field. Thanks!

**Comment by Haeki** [comment]
Hi,
looks good to me. I did a quick test run and it worked as expected.

**Comment by synackray** [comment]
Thanks! After final testing I'll be moving this into `master`. It should be done by the end of the week. Thanks again for the report and help!
